version: '3.8'

services:
  app:
    build: .
    container_name: twitter_clone
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on: []
